version: "3.1"

services:

    db:
        image: postgres:alpine
        restart: always
        healthcheck:
            test: psql postgres --command "select 1" -U postgres
        environment:
            - "POSTGRES_USER=poldex"
            - "POSTGRES_PASSWORD=poldex"
            - "POSTGRES_DB=tna"
        ports:
            - "5432:5432"
        volumes:
            - "poldex-db:/var/lib/postgresql/data"

volumes:
    poldex-db: