### Application
app:
    tna-admin-login: poldex
    tna-admin-password: poldex

#### Server
server:
    port: 8080
    servlet:
        context-path: /api

errors:
    expose-arguments: ALWAYS

### Spring Data
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/tna
        username: poldex
        password: poldex
    jpa:
        hibernate.ddl-auto: validate
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        open-in-view: false
    liquibase:
        change-log: 'classpath:db/changelog/db.changelog-master.yaml'